[package]
name = "tomlrs-php"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-php = "*"
ext-php-rs = "0.7.3"
toml = "*"

[lib]
crate-type = ["cdylib"]
